export const ex = [
  { value: 1, label: "cats" },
  { value: 2, label: "dogs" },
  { value: 3, label: "animals" },
  { value: 4, label: "food" },
  { value: 5, label: "sports" },
  { value: 6, label: "geography" },
  { value: 7, label: "history" },
  { value: 8, label: "music" },
  { value: 9, label: "movies" },
  { value: 10, label: "tv" },
  { value: 11, label: "science" },
  { value: 12, label: "math" },
  { value: 13, label: "general" },
];
