export const ex = [
  { value: 1, label: "cats" },
  { value: 2, label: "dogs" },
  { value: 21, label: "animals" },
  { value: 23, label: "food" },
  { value: 25, label: "sports" },
  { value: 26, label: "geography" },
  { value: 24, label: "history" },
  { value: 232, label: "music" },
  { value: 225, label: "movies" },
  { value: 27, label: "tv" },
  { value: 28, label: "science" },
  { value: 234, label: "math" },
  { value: 278, label: "general" },
];
